# Generated by Django 2.2.6 on 2019-10-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191005_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dep',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
