# Generated by Django 2.2.6 on 2019-10-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='entry',
            field=models.TextField(max_length=1000),
        ),
    ]
