# Generated by Django 2.2.6 on 2019-10-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191006_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='entry',
            field=models.TextField(max_length=3000),
        ),
    ]
